### ISSUE TITLE
Make geodata accessible from the web

### ISSUE THREAD

**Issue by philboeselager** [hbz/geodata#19]
In order to use geodata in integration tests (like in hbz/lobid-organisations), this microservice should be accessible from the web resp. under a constant URL. Therefore, find a suitable (sub-) domain and make geodata be accessible that way.

**Comment by fsteeg** [comment]
We discussed the role of the geodata service today and came to the conclusion that we should consider this an internal component to be used by our products, not a public product in itself. For the testing issue, we'll have to find a different solution. Its own test will run fine, and lobid-organisations skips unsuccessful attempts to call the service. Closing.
