### ISSUE TITLE
Use 'geodata' path prefix

### ISSUE THREAD

**Issue by fsteeg** [hbz/geodata#25]
All routes should be prefixed with 'geodata'.

See new data module specification at: http://hbz.github.io/#data-module-specification

**Comment by fsteeg** [comment]
Blocked by https://github.com/hbz/geodata/issues/34, which is blocked by https://github.com/hbz/geodata/issues/23, which is `ready` for work. Unassigning and moving to backlog.

**Comment by SBRitter** [comment]
This should be fixed by https://github.com/hbz/geodata/pull/33. Thus, closing this issue.
