### ISSUE TITLE
Special char (umlaut) handling on server

### ISSUE THREAD

**Issue by philboeselager** [hbz/geodata#35]
Though working on DEV machine, umlauts are not processed properly on gaia.

**Comment by philboeselager** [comment]
Looks like a classic character encoding mismatch between my request sending dev machine (ISO-8859-1) and the receiving app on the server (UTF-8). Holds for "wikidata" requests as well as for "lat" / "long" / "postcode" requests. As it doesn't affect the results when called UTF-8 encoded calls, I recommend to close this issue. @fsteeg : do you agree?

**Comment by dr0i** [comment]
I hardcoded locale settings to `de_DE.UTF-8` via `.profile`, as it is already on quaoar1. Maybe this fixes the umlaut problem. Please restart again and test.

**Comment by acka47** [comment]
The problem is indeed fixed (see e.g. http://gaia.hbz-nrw.de:7400/geodata?q=K%C3%B6ln), I already closed #21. Closing this one as well.
