### ISSUE TITLE
Use embedded Elasticsearch index

### ISSUE THREAD

**Issue by fsteeg** [hbz/geodata#36]
The current geodata index size is only 3.5 MB. To ease deployment and increase self-containedness, we should use an embedded Elasticsearch index as we do in lobid-organisations. Since filling up the geodata index takes time, the index should _not_ be recreated on app start (unlike lobid-organisations).

**Comment by SBRitter** [comment]
Deployed to quaoar1: http://quaoar1.hbz-nrw.de:9001/geodata?q=buxtehude

**Comment by fsteeg** [comment]
Staging instance should run on port 7401 (current prod service runs on 7400).

You can assign me for functional review too, I don't think there's anything to review for @acka47 here at this point.

**Comment by SBRitter** [comment]
Now deployed on quaoar1 with port 7401: http://quaoar1.hbz-nrw.de:7401/geodata?q=buxtehude

**Comment by fsteeg** [comment]
OK, now as the next step, we should configure lobid-organisations-staging to use this geodata-staging instance in the transformation (i.e. delete enriched.out.json, configure geodata in conf file, restart).

**Comment by SBRitter** [comment]
Deployed to staging: http://test.lobid.org/organisations

lobid-organisations-staging now uses geodata von quaoar1 (http://quaoar1.hbz-nrw.de:7401).

**Comment by fsteeg** [comment]
+1
