### ISSUE TITLE
Connect to geonames

### ISSUE THREAD

**Issue by philboeselager** [hbz/geodata#46]
[Geonames](http://www.geonames.org/) is a promising service that might be helpful. Maybe we could add it as a third data source.

**Comment by philboeselager** [comment]
Sidenote: geonames can also be used in OpenRefine by using [geonames-reconcile](https://github.com/cmh2166/geonames-reconcile).

**Comment by dr0i** [comment]
Hi @philboeselager, we set up the geo-api https://github.com/pelias which uses many different databases including geonames. Our experiences with it are so far very good! Ultimately, I think this repo here can be closed one day.
